const allSearchItems = [

    { name: "Schussverletzung", page: "Verletzungen.html", id: "schussverletzung" },
    { name: "Schnittwunden", page: "Verletzungen.html", id: "schnittwunden" },
    { name: "Stumpfe Gewalt (Prellung, Faustschlag...)", page: "Verletzungen.html", id: "stumpfe gewalt" },
    { name: "Gehirnerschütterung", page: "Verletzungen.html", id: "gehirnerschütterung" },
    { name: "Fraktur (Bruch)", page: "Verletzungen.html", id: "fraktur" },
    { name: "Gelenkverletzungen", page: "Verletzungen.html", id: "gelenkverletzungen" },
    { name: "Brandwunden", page: "Verletzungen.html", id: "brandwunden" },
    { name: "Kälteverletzungen", page: "Verletzungen.html", id: "kälteverletzungen" },
    { name: "Spezifische Verletzungen (Innere, Auge, Pneumothorax)", page: "Verletzungen.html", id: "spezifische verletzungen" },
    { name: "Tierbisse", page: "Verletzungen.html", id: "tierbisse" },


    { name: "Pest", page: "Krankheiten.html", id: "pest" },
    { name: "Cholera", page: "Krankheiten.html", id: "cholera" },
    { name: "Typhus", page: "Krankheiten.html", id: "typhus" },
    { name: "Tuberkulose", page: "Krankheiten.html", id: "tuberkulose" },
    { name: "Diphtherie", page: "Krankheiten.html", id: "diphtherie" },
    { name: "Masern", page: "Krankheiten.html", id: "masern" },
    { name: "Keuchhusten", page: "Krankheiten.html", id: "keuchhusten" },
    { name: "Grippe / Influenza", page: "Krankheiten.html", id: "grippe" },
    { name: "Pocken", page: "Krankheiten.html", id: "pocken" },
    { name: "Wundfieber / Gangrän", page: "Krankheiten.html", id: "wundfieber" },
    { name: "Durchfall / Cholera-artige Symptome", page: "Krankheiten.html", id: "durchfall" },
    { name: "Syphilis", page: "Krankheiten.html", id: "syphilis" },
    { name: "Gonorrhoe", page: "Krankheiten.html", id: "gonorrhoe" },
    { name: "Anämie", page: "Krankheiten.html", id: "anämie" },
    { name: "Malaria", page: "Krankheiten.html", id: "malaria" },
    { name: "Gelbsucht / Hepatitis", page: "Krankheiten.html", id: "gelbsucht" },
    { name: "Nierenentzündung", page: "Krankheiten.html", id: "nierenentzündung" },
    { name: "Ringelflechte", page: "Krankheiten.html", id: "ringelflechte" },
    { name: "Ekzeme", page: "Krankheiten.html", id: "ekzeme" },
    { name: "Frostbeulen", page: "Krankheiten.html", id: "frostbeulen" },
    { name: "Hitzeschlag / Sonnenstich", page: "Krankheiten.html", id: "hitzeschlag" },
    { name: "Melancholie / Depression", page: "Krankheiten.html", id: "melancholie" },
    { name: "Wahnsinn / Epilepsie / Hysterie", page: "Krankheiten.html", id: "wahnsinn" },


    { name: "Kopfschmerzen", page: "Beschwerden.html", id: "kopfschmerzen" },
    { name: "Fieber / Schüttelfrost", page: "Beschwerden.html", id: "fieber" },
    { name: "Übelkeit / Erbrechen", page: "Beschwerden.html", id: "übelkeit" },
    { name: "Durchfall / Magenbeschwerden", page: "Beschwerden.html", id: "magenbeschwerden" },
    { name: "Erkältung / laufende Nase", page: "Beschwerden.html", id: "erkältung" },
    { name: "Halsschmerzen / Schluckbeschwerden", page: "Beschwerden.html", id: "halsschmerzen" },
    { name: "Husten / Atembeschwerden", page: "Beschwerden.html", id: "atembeschwerden" },
    { name: "Rückenschmerzen / Bandscheibenprobleme", page: "Beschwerden.html", id: "rückenschmerzen" },
    { name: "Gelenkschmerzen / Arthritis", page: "Beschwerden.html", id: "gelenkschmerzen" },
    { name: "Schlaflosigkeit / Nervosität", page: "Beschwerden.html", id: "schlaflosigkeit" },
    { name: "Zahnschmerzen / Karies", page: "Beschwerden.html", id: "zahnschmerzen" },
    { name: "Chronische Müdigkeit / Erschöpfung", page: "Beschwerden.html", id: "müdigkeit" },
    { name: "Sehstörungen / Augenprobleme", page: "Beschwerden.html", id: "sehstörungen" },
    { name: "Schlechte Wundheilung / Eiterungen", page: "Beschwerden.html", id: "wundheilung" },
    { name: "Allergien / Hautreaktionen", page: "Beschwerden.html", id: "allergien" },
    { name: "Angst / Panikattacken", page: "Beschwerden.html", id: "panikattacken" },
    { name: "Asthma / Atemnot", page: "Beschwerden.html", id: "asthma" },
    { name: "Hautausschläge / Ekzeme / Wundinfektionen", page: "Beschwerden.html", id: "hautausschläge" },
    { name: "Blutungen / innere Blutungen", page: "Beschwerden.html", id: "blutungen" },
    { name: "Schock / Bewusstlosigkeit", page: "Beschwerden.html", id: "schock" },


    { name: "Aspirin", page: "Medikamente.html", id: "aspirin" },
    { name: "Antipyrin", page: "Medikamente.html", id: "antipyrin" },
    { name: "Phenacetin", page: "Medikamente.html", id: "phenacetin" },
    { name: "Bromide", page: "Medikamente.html", id: "bromide" },
    { name: "Brechmittel", page: "Medikamente.html", id: "brechmittel" },
    { name: "Morphin", page: "Medikamente.html", id: "morphin" },
    { name: "Kokain", page: "Medikamente.html", id: "kokain" },
    { name: "Laudanum (Opiumtinktur)", page: "Medikamente.html", id: "laudanum" },
    { name: "Arnika-Tinktur", page: "Medikamente.html", id: "arnika-tinktur" },
    { name: "Heroin-Tinktur", page: "Medikamente.html", id: "heroin-tinktur" },
    { name: "Codein-Tinktur", page: "Medikamente.html", id: "codein-tinktur" },
    { name: "Chinin-Lösung", page: "Medikamente.html", id: "chinin-lösung" },
    { name: "Chininpulver", page: "Medikamente.html", id: "chininpulver" },
    { name: "Salicylsäure", page: "Medikamente.html", id: "salicylsäure" },
    { name: "Rizinusöl", page: "Medikamente.html", id: "rizinusöl" },
    { name: "Kamillentee", page: "Medikamente.html", id: "kamillentee" },
    { name: "Pfefferminztee", page: "Medikamente.html", id: "pfefferminztee" },
    { name: "Salbeitee", page: "Medikamente.html", id: "salbeitee" },
    { name: "Schmerz-Hustenpastillen", page: "Medikamente.html", id: "schmerz-hustenpastillen" },
    { name: "Mentholpastillen", page: "Medikamente.html", id: "mentholpastillen" },
    { name: "Opiumelixir", page: "Medikamente.html", id: "opiumelixir" },
    { name: "Fiebertonikum", page: "Medikamente.html", id: "fiebertonikum" },
    { name: "Bronchialelixir", page: "Medikamente.html", id: "bronchialelixir" },
    { name: "Frauengold", page: "Medikamente.html", id: "frauengold" },
    { name: "Fingerhutextrakt", page: "Medikamente.html", id: "fingerhutextrakt" },
    { name: "Chloroform", page: "Medikamente.html", id: "chloroform" },
    { name: "Äther", page: "Medikamente.html", id: "äther" },
    { name: "Diphtherie-Serum", page: "Medikamente.html", id: "diphtherie-serum" },
    { name: "Kochsalzlösung", page: "Medikamente.html", id: "kochsalzlösung" },
    { name: "Glukoselösungen", page: "Medikamente.html", id: "glukoselösungen" },
    { name: "Carbolsäure", page: "Medikamente.html", id: "carbolsäure" },
    { name: "Jodlösung", page: "Medikamente.html", id: "jodlösung" },
    { name: "hochprozentiger Alkohol", page: "Medikamente.html", id: "hochprozentiger alkohol" },
    { name: "Quecksilberverbindungen", page: "Medikamente.html", id: "quecksilberverbindungen" },
    { name: "Senfpflaster", page: "Medikamente.html", id: "senfpflaster" },
    { name: "Grove’s Tasteless Chill Tonic", page: "Medikamente.html", id: "grove" },
    { name: "Angostura Bitters", page: "Medikamente.html", id: "angostura" },
    { name: "Dr. Boyce’s Tonic Bitters", page: "Medikamente.html", id: "boyce" },
    { name: "Liebig’s Malt Extract", page: "Medikamente.html", id: "liebig" },
    { name: "Coca-Cola", page: "Medikamente.html", id: "coca-cola" },
    { name: "Belladonna", page: "Medikamente.html", id: "belladonna" },
    { name: "Zinksalbe", page: "Medikamente.html", id: "zinksalbe" },
    { name: "Bienenwachs-Salbe", page: "Medikamente.html", id: "bienenwachs-salbe" },
    { name: "Opiumsalbe", page: "Medikamente.html", id: "opiumsalbe" },
    { name: "Calomel-Salbe", page: "Medikamente.html", id: "calomel-salbe" },
    { name: "Arnikasalbe", page: "Medikamente.html", id: "arnikasalbe" },
    { name: "Mentholsalbe", page: "Medikamente.html", id: "mentholsalbe" },


    { name: "Skalpell", page: "ausruestung.html", id: "skalpell" },
    { name: "Chirurgische Messer", page: "ausruestung.html", id: "chirurgische messer" },
    { name: "Amputationsmesser", page: "ausruestung.html", id: "amputationsmesser" },
    { name: "Tenotom", page: "ausruestung.html", id: "tenotom" },
    { name: "Lanzetten", page: "ausruestung.html", id: "lanzetten" },
    { name: "Chirurgische Scheren", page: "ausruestung.html", id: "chirurgische scheren" },
    { name: "Verbandsscheren", page: "ausruestung.html", id: "verbandsscheren" },
    { name: "Nahtscheren", page: "ausruestung.html", id: "nahtscheren" },
    { name: "Knochenscheren", page: "ausruestung.html", id: "knochenscheren" },
    { name: "Chirurgische Pinzetten", page: "ausruestung.html", id: "chirurgische pinzetten" },
    { name: "Anatomische Pinzetten", page: "ausruestung.html", id: "anatomische pinzetten" },
    { name: "Gefäßklemmen", page: "ausruestung.html", id: "gefäßklemmen" },
    { name: "Arterienklemmen", page: "ausruestung.html", id: "arterienklemmen" },
    { name: "Knochenzangen", page: "ausruestung.html", id: "knochenzangen" },
    { name: "Kugelzangen", page: "ausruestung.html", id: "kugelzangen" },
    { name: "Wundhaken", page: "ausruestung.html", id: "wundhaken" },
    { name: "Retraktoren", page: "ausruestung.html", id: "retraktoren" },
    { name: "Hautspreizer", page: "ausruestung.html", id: "hautspreizer" },
    { name: "Chirurgische Nadeln", page: "ausruestung.html", id: "chirurgische nadeln" },
    { name: "Nahtnadeln", page: "ausruestung.html", id: "nahtnadeln" },
    { name: "Sonden", page: "ausruestung.html", id: "sonden" },
    { name: "Kathetersonden", page: "ausruestung.html", id: "kathetersonden" },
    { name: "Knochensägen", page: "ausruestung.html", id: "knochensägen" },
    { name: "Gigli-Drahtsägen", page: "ausruestung.html", id: "gigli-drahtsägen" },
    { name: "Trepanationsbohrer (manuell)", page: "ausruestung.html", id: "trepanationsbohrer" },
    { name: "Chirurgische Meißel", page: "ausruestung.html", id: "chirurgische meißel" },
    { name: "Knochenhammer", page: "ausruestung.html", id: "knochenhammer" },
    { name: "Knochenraspeln", page: "ausruestung.html", id: "knochenraspeln" },
    { name: "Verbandmaterial", page: "ausruestung.html", id: "verbandmaterial" },
    { name: "Mull", page: "ausruestung.html", id: "mull" },
    { name: "Baumwolle", page: "ausruestung.html", id: "baumwolle" },
    { name: "Gazeverbände", page: "ausruestung.html", id: "gazeverbände" },
    { name: "Kompressen", page: "ausruestung.html", id: "kompressen" },
    { name: "Verbandrollen", page: "ausruestung.html", id: "verbandrollen" },
    { name: "Gipsverbände", page: "ausruestung.html", id: "gipsverbände" },
    { name: "Schienen", page: "ausruestung.html", id: "schienen" },
    { name: "Wunddrainagen", page: "ausruestung.html", id: "wunddrainagen" },
    { name: "Gummidrains", page: "ausruestung.html", id: "gummidrains" },
    { name: "Injektion", page: "ausruestung.html", id: "injektion" },
    { name: "Metall-Spritzen", page: "ausruestung.html", id: "metall-spritzen" },
    { name: "Hypodermische Nadeln", page: "ausruestung.html", id: "hypodermische nadeln" },
    { name: "Infusionsflaschen", page: "ausruestung.html", id: "infusionsflaschen" },
    { name: "Infusionsschläuche", page: "ausruestung.html", id: "infusionsschläuche" },
    { name: "Tropfgestelle", page: "ausruestung.html", id: "tropfgestelle" },
    { name: "Klistierspritzen", page: "ausruestung.html", id: "klistierspritzen" },
    { name: "Irrigatoren", page: "ausruestung.html", id: "irrigatoren" },
    { name: "Stethoskop", page: "ausruestung.html", id: "stethoskop" },
    { name: "Thermometer", page: "ausruestung.html", id: "thermometer" },
    { name: "Reflexhammer", page: "ausruestung.html", id: "reflexhammer" },
    { name: "Augenspiegel", page: "ausruestung.html", id: "augenspiegel" },
    { name: "Ohrenspiegel", page: "ausruestung.html", id: "ohrenspiegel" },
    { name: "Zungenspatel", page: "ausruestung.html", id: "zungenspatel" },
    { name: "Untersuchungslampen", page: "ausruestung.html", id: "untersuchung" },
    { name: "Lupen", page: "ausruestung.html", id: "lupen" }, 


    { name: "Schafgarbe (Yarrow)", page: "Pflanzen.html", id: "schafgarbe" },
    { name: "Ginseng", page: "Pflanzen.html", id: "ginseng" },
    { name: "Klettenwurzel (Burdock Root)", page: "Pflanzen.html", id: "klettenwurzel" },
    { name: "Rohrkolben (Bulrush)", page: "Pflanzen.html", id: "rohrkolben" },
    { name: "Thymian", page: "Pflanzen.html", id: "thymian" },
    { name: "Wüstensalbei", page: "Pflanzen.html", id: "wuestensalbei" },
    { name: "Muskatgarbe", page: "Pflanzen.html", id: "muskatgarbe" },
    { name: "Kolibrisalbei", page: "Pflanzen.html", id: "kolibrisalbei" },
    { name: "Indianertabak", page: "Pflanzen.html", id: "indianertabak" },
    { name: "Seidenpflanze (Milkweed)", page: "Pflanzen.html", id: "seidenpflanze" },
    { name: "Oleandersalbei", page: "Pflanzen.html", id: "oleandersalbei" },
    { name: "Oregano", page: "Pflanzen.html", id: "oregano" },
    { name: "Präriemohn", page: "Pflanzen.html", id: "praeriemohn" },
    { name: "Vanilleblume", page: "Pflanzen.html", id: "vanilleblume" },
    { name: "Schneeglöckchen", page: "Pflanzen.html", id: "schneegloeckchen" },
    { name: "Wilde Möhre", page: "Pflanzen.html", id: "wilde_moehre" },
    { name: "Mutterkraut", page: "Pflanzen.html", id: "mutterkraut" },
    { name: "Wilde Minze", page: "Pflanzen.html", id: "wilde_minze" },
    { name: "Beeren", page: "Pflanzen.html", id: "beeren" },
    { name: "Pilze", page: "Pflanzen.html", id: "pilze" },
    { name: "Arnika", page: "Pflanzen.html", id: "arnika" },
    { name: "Brennnessel", page: "Pflanzen.html", id: "brennnessel" },
    { name: "Baldrian", page: "Pflanzen.html", id: "baldrian" },
    { name: "Kamille", page: "Pflanzen.html", id: "kamille" },
    { name: "Fingerhut", page: "Pflanzen.html", id: "fingerhut" },
    { name: "Tollkirsche", page: "Pflanzen.html", id: "tollkirsche" }
];
